# -*- coding: utf-8 -*-
"""perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBkRx3zcZqLB5_Zuq6uHAsPLXGc655Hl
"""

import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import cross_val_score as sklearn_cv_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from cross_val_score import cross_val_score

# Load data
data = load_breast_cancer()
X, y = data.data, data.target

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize model
clf = LogisticRegression(max_iter=500)

# Our custom cross-validation
scores_custom = cross_val_score(clf, X_scaled, y, cv=5, scoring='f1-score', random_state=42)
print(f"Custom cross_val_score (F1): {scores_custom}")
print(f"Mean score: {scores_custom.mean():.4f}")

# Sklearn cross_val_score for comparison
scores_sklearn = sklearn_cv_score(clf, X_scaled, y, cv=5, scoring='f1')
print(f"Sklearn cross_val_score (F1): {scores_sklearn}")
print(f"Mean score: {scores_sklearn.mean():.4f}")